[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
# It is strongly suggested to use encrypted mnemonics to avoid putting
# seed phrases directly into TOML files.  To do so, run:
#
#     clarinet deployments encrypt
#
# Enter your seed phrase and a password, then paste the encrypted mnemonic here.
#
# Otherwise, use the mnemonic field below:
encrypted_mnemonic = "G9FyY374r4VvMXDSUi6rArPVfRygcp8RsHvPVtg3c7ofsKttu56RuYLehQyX2ZHUautzxVBWmGu8Sw1S2ZCdVYSBXPABKECH5f66fNVAAzBsEVdZnFy9YdSJ2qDFLiQiawrqbuDcNBESicTaSRmLSHaWARuqNnwbCzyo43iykLW2zuSMLogsGH7MgyXsbWezfE5PxJfmQuPmfrSbiXqQCPX28W64YSukB4j7dDo8avGxb7imSjKp84JKRCc"
